### ISSUE TITLE
Rockradio, Jazzradio and classic radio networks not playing

### ISSUE THREAD

**Issue by Tanmoysarma** [ssapalski/plugin.audio.addict#9]
I checked in SPMC, Kodi Krypton. only Radiotunes and DI appear to be playing. Did they change their URLs again ?

**Comment by ssapalski** [comment]
I will check it!

**Comment by ssapalski** [comment]
The icecast servers of these networks have been shut down. Via the API I can't get the stream URLs anymore, at least no URL which would work. I try to research another possibility on how to get the URLs since the websites are still online and the streams are working on these.

Unfortunately this won't happen anytime soon!

**Comment by Tanmoysarma** [comment]
Thanks for looking into it.

**Comment by gmircea** [comment]
Any progress on this ? Or ... is it going to happen ? 
regards

**Comment by dirkpitt1967** [comment]
Hi, 
v 0.5.1 don't work for me. When a new version of the plugin (maybe 0.5.2) ?
Thanks in advance
Dirk

**Comment by ssapalski** [comment]
Sorry but I have no time to work on this issue. I might change the plugin to only support premium in the future or disable networks which aren't accessible for free anymore via shoutcast.

This is for sure not what you want to hear, but all what I can offer.

**Comment by ssapalski** [comment]
Please have a look in the Kodi Forum: [link](https://forum.kodi.tv/showthread.php?tid=317155&pid=2708528#pid2708528)
I'm sorry but I will abandon public stream support and only maintain premium from now on.
